apiVersion: flwr.dev/v1
kind: FLDeployment
metadata:
  name: fl-deployment
  finalizers:
spec:
  server:
    imagePullPolicy: IfNotPresent
    port: 8080
    rounds: 2
  client:
    num_clients: 3
    imagePullPolicy: IfNotPresent
    isolation: True
    port: 30051
    dataset:
      path: /mnt/data
      download: False
    privacy:
      budget: 0.2
